name: Build Docker Image

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      dockerfile_path:
        type: string
        required: true
        default: ./Dockerfile
      image_tag:
        type: string
        required: true
      container_registry_url:
        type: string
        required: false
        default: 904705273474.dkr.ecr.us-east-1.amazonaws.com
      container_repository_path:
        type: string
        required: true
      aws_region:
        type: string
        required: false
        default: us-east-1
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      build_args:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ${{ github.ref_name }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Restore cached layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-build
          restore-keys: |
            docker-build
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: ${{ inputs.dockerfile_path }}
          build-args: ${{ secrets.build_args }}
          tags: ${{ inputs.container_registry_url }}/${{ inputs.container_repository_path }}:${{ inputs.image_tag }},${{ inputs.container_registry_url }}/${{ inputs.container_repository_path }}:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Save layers cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
