name: Deploy Kubernetes App

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app_name:
        type: string
        required: true
      app_version:
        type: string
        required: true
      author_name:
        type: string
        required: false
        default: Deploy Job
      author_email:
        type: string
        required: false
        default: deploy@fohr.co

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Helm charts repository
        uses: actions/checkout@v3
        with:
          repository: "fohrcard/helm-charts"
          ref: ${{ inputs.environment == 'production' && 'main' || 'staging' }}
          ssh-key: ${{ secrets.HELM_CHARTS_DEPLOY_KEY }}

      - name: Update app version
        run: |
          git config --global user.name "${{ inputs.author_name }}"
          git config --global user.email "${{ inputs.author_email }}"
          echo "appVersion: ${{ inputs.app_version }}" > apps/${{ inputs.app_name }}/version/${{ inputs.environment }}-version.yaml
          git add apps/${{ inputs.app_name }}/version/${{ inputs.environment }}-version.yaml
          git commit -m "deploy ${{ inputs.environment }} ${{ inputs.app_name }} version ${{ inputs.app_version }}"
          git push -u origin ${{ inputs.environment == 'production' && 'main' || 'staging' }}
