name: Publish NPM package

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        required: true
        default: "16"
    secrets:
      npm_registry_token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency: ${{ github.ref_name }}
    steps:
      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm

      - name: Download dependencies
        run: npm ci

      - name: Build and Publish
        run: npm publish
        env:
          NPM_REGISTRY_TOKEN: ${{ secrets.npm_registry_token }}
